using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Botany.Ui;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void DisplayMessage(FormattedMessage message)
    {
        TextDisplay.SetMessage(message);
    }
}
