using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.PlantAnalyzer;
using static Content.Client.Stylesheets.StyleNano;

namespace Content.Client.Botany.Ui;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        InfoButton.OnPressed += _ => Tabs.CurrentTab = 0;
        ChemButton.OnPressed += _ => Tabs.CurrentTab = 1;
        MutButton.OnPressed += _ => Tabs.CurrentTab = 2;

        TabContainer.SetTabTitle(InfoTab, "Info");
        TabContainer.SetTabTitle(ChemTab, "Chemicals");
        TabContainer.SetTabTitle(MutTab, "Mutations");
    }

    public void DisplayInfo(PlantAnalyzerScannedMessage msg)
{
    InfoContainer.DisposeAllChildren();
    ChemContainer.DisposeAllChildren();
    MutContainer.DisposeAllChildren();

    AddHeader(InfoContainer, "SCANNER DE PLANTAS");

    AddHeader(InfoContainer, msg.IsPlant ? "INFORMAÇÕES DA PLANTA" : "INFORMAÇÕES DA SEMENTE");

    var seed = msg.Seed;
    AddGrid(InfoContainer,
            ("Nome", seed.Name),
            ("Nome de Exibição", seed.DisplayName),
            ("Tipo", seed.Noun));

    AddHeader(InfoContainer, "GENÉTICA");
    AddGrid(InfoContainer,
            ("Potência", seed.Potency.ToString()),
            ("Rendimento", seed.Yield.ToString()),
            ("Maturação", $"{seed.Maturation} ciclos"),
            ("Vida Máxima", seed.Endurance.ToString()),
            ("Tempo de Vida", $"{seed.Lifespan} ciclos"),
            ("Produção", seed.Production.ToString()),
            ("Pode gerar sementes", seed.Seedless ? "Não" : "Sim"));

    if (msg.IsPlant && msg.Holder is { } holder)
    {
        AddHeader(InfoContainer, "STATUS DA PLANTA");
        AddGrid(InfoContainer,
                ("Saúde", $"{holder.Health}/{seed.Endurance}"),
                ("Idade", $"{holder.Age} ciclos"),
                ("Pronta para colheita", holder.HarvestReady ? "Sim" : "Não"),
                ("Amostrada", holder.Sampled ? "Sim" : "Não"),
                ("Estado", holder.Dead ? "Morta" : "Saudável"),
                ("Viabilidade Genética", seed.Viable ? "Saudável" : "Defeituosa"));

        AddHeader(InfoContainer, "CONDIÇÕES DO VASO");
        AddGrid(InfoContainer,
                ("Água", $"{holder.WaterLevel}/100"),
                ("Nutrientes", $"{holder.NutritionLevel}/100"),
                ("Toxinas", holder.Toxins.ToString()),
                ("Pragas", holder.PestLevel.ToString()),
                ("Ervas daninhas", holder.WeedLevel.ToString()));

        AddHeader(InfoContainer, "AVISOS AMBIENTAIS");
        AddGrid(InfoContainer,
                ("Temperatura", holder.ImproperHeat ? "Incorreta" : "OK"),
                ("Pressão", holder.ImproperPressure ? "Incorreta" : "OK"),
                ("Luz", holder.ImproperLight ? "Incorreta" : "OK"));
    }

    AddHeader(InfoContainer, "CONSUMO");
    AddGrid(InfoContainer,
            ("Água", $"{seed.WaterConsumption} por ciclo"),
            ("Nutrientes", $"{seed.NutrientConsumption} por ciclo"));

    AddHeader(InfoContainer, "TOLERÂNCIAS");
    AddGrid(InfoContainer,
            ("Luz", $"Ideal {seed.IdealLight} ± {seed.LightTolerance}"),
            ("Temperatura", $"Ideal {seed.IdealHeat} ± {seed.HeatTolerance}"),
            ("Pressão", $"{seed.LowPressureTolerance} - {seed.HighPressureTolerance} kPa"),
            ("Toxinas", $"até {seed.ToxinsTolerance}"),
            ("Pragas", $"até {seed.PestTolerance}"),
            ("Ervas daninhas", $"até {seed.WeedTolerance}"));

    AddHeader(ChemContainer, "QUÍMICOS");
    if (seed.Chemicals.Count > 0)
    {
        foreach (var chem in seed.Chemicals)
            AddLabel(ChemContainer, $"- {chem.Id} (Min: {chem.Min}, Max: {chem.Max}, PotDiv: {chem.PotDiv})");
    }
    else
    {
        AddLabel(ChemContainer, "Nenhum químico presente.");
    }

    AddHeader(MutContainer, "MUTAÇÕES ATIVAS");
    if (seed.Mutations.Count > 0)
    {
        foreach (var mut in seed.Mutations)
            AddLabel(MutContainer, $"- {mut}");
    }
    else
    {
        AddLabel(MutContainer, "Nenhuma mutação.");
    }
}

private static void AddHeader(BoxContainer container, string text)
{
    var label = new Label { Text = text };
    label.AddStyleClass(StyleClassLabelBig);
    container.AddChild(label);
    container.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });
}

private static void AddGrid(BoxContainer container, params (string, string)[] entries)
{
    var grid = new GridContainer { Columns = 2 };
    foreach (var (key, value) in entries)
    {
        grid.AddChild(new Label { Text = key });
        grid.AddChild(new Label { Text = value });
    }
    container.AddChild(grid);
    container.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });
}

private static void AddLabel(BoxContainer container, string text)
{
    container.AddChild(new Label { Text = text });
}
}
