using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.PlantAnalyzer;
using static Content.Client.Stylesheets.StyleNano;

namespace Content.Client.Botany.Ui;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void DisplayInfo(PlantAnalyzerScannedMessage msg)
{
    SectionContainer.DisposeAllChildren();

    AddHeader("SCANNER DE PLANTAS");

    AddHeader(msg.IsPlant ? "INFORMAÇÕES DA PLANTA" : "INFORMAÇÕES DA SEMENTE");

    var seed = msg.Seed;
    AddGrid(("Nome", seed.Name),
            ("Nome de Exibição", seed.DisplayName),
            ("Tipo", seed.Noun));

    AddHeader("GENÉTICA");
    AddGrid(("Potência", seed.Potency.ToString()),
            ("Rendimento", seed.Yield.ToString()),
            ("Maturação", $"{seed.Maturation} ciclos"),
            ("Vida Máxima", seed.Endurance.ToString()),
            ("Tempo de Vida", $"{seed.Lifespan} ciclos"),
            ("Produção", seed.Production.ToString()),
            ("Pode gerar sementes", seed.Seedless ? "Não" : "Sim"));

    if (msg.IsPlant && msg.Holder is { } holder)
    {
        AddHeader("STATUS DA PLANTA");
        AddGrid(("Saúde", $"{holder.Health}/{seed.Endurance}"),
                ("Idade", $"{holder.Age} ciclos"),
                ("Pronta para colheita", holder.HarvestReady ? "Sim" : "Não"),
                ("Amostrada", holder.Sampled ? "Sim" : "Não"),
                ("Estado", holder.Dead ? "Morta" : "Saudável"),
                ("Viabilidade Genética", seed.Viable ? "Saudável" : "Defeituosa"));

        AddHeader("CONDIÇÕES DO VASO");
        AddGrid(("Água", $"{holder.WaterLevel}/100"),
                ("Nutrientes", $"{holder.NutritionLevel}/100"),
                ("Toxinas", holder.Toxins.ToString()),
                ("Pragas", holder.PestLevel.ToString()),
                ("Ervas daninhas", holder.WeedLevel.ToString()));

        AddHeader("AVISOS AMBIENTAIS");
        AddGrid(("Temperatura", holder.ImproperHeat ? "Incorreta" : "OK"),
                ("Pressão", holder.ImproperPressure ? "Incorreta" : "OK"),
                ("Luz", holder.ImproperLight ? "Incorreta" : "OK"));
    }

    AddHeader("CONSUMO");
    AddGrid(("Água", $"{seed.WaterConsumption} por ciclo"),
            ("Nutrientes", $"{seed.NutrientConsumption} por ciclo"));

    AddHeader("TOLERÂNCIAS");
    AddGrid(("Luz", $"Ideal {seed.IdealLight} ± {seed.LightTolerance}"),
            ("Temperatura", $"Ideal {seed.IdealHeat} ± {seed.HeatTolerance}"),
            ("Pressão", $"{seed.LowPressureTolerance} - {seed.HighPressureTolerance} kPa"),
            ("Toxinas", $"até {seed.ToxinsTolerance}"),
            ("Pragas", $"até {seed.PestTolerance}"),
            ("Ervas daninhas", $"até {seed.WeedTolerance}"));

    AddHeader("QUÍMICOS");
    if (seed.Chemicals.Count > 0)
    {
        foreach (var chem in seed.Chemicals)
            AddLabel($"- {chem.Id} (Min: {chem.Min}, Max: {chem.Max}, PotDiv: {chem.PotDiv})");
    }
    else
    {
        AddLabel("Nenhum químico presente.");
    }

    AddHeader("MUTAÇÕES ATIVAS");
    if (seed.Mutations.Count > 0)
    {
        foreach (var mut in seed.Mutations)
            AddLabel($"- {mut}");
    }
    else
    {
        AddLabel("Nenhuma mutação.");
    }
}

private void AddHeader(string text)
{
    var label = new Label { Text = text };
    label.AddStyleClass(StyleClassLabelBig);
    SectionContainer.AddChild(label);
    SectionContainer.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });
}

private void AddGrid(params (string, string)[] entries)
{
    var grid = new GridContainer { Columns = 2 };
    foreach (var (key, value) in entries)
    {
        grid.AddChild(new Label { Text = key });
        grid.AddChild(new Label { Text = value });
    }
    SectionContainer.AddChild(grid);
    SectionContainer.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });
}

private void AddLabel(string text)
{
    SectionContainer.AddChild(new Label { Text = text });
}
}
